### ISSUE TITLE
How to use correctly

### ISSUE THREAD

**Issue by deeco** [HillLiu/cloudflare-bash-util#1]
Im interested in using this to add records , what is the syntax or guide?

**Comment by HillLiu** [comment]
@deeco Thanks for open issue.

I add logging function.

You could simple enable it with .env and set LOG_ENABLED to on.
https://github.com/HillLiu/cloudflare-bash-util/blob/master/.env.sample#L11-L13
```
LOG_FILE=/tmp/result.log
ERROR_LOG_FILE=/tmp/error.log
LOG_ENABLED=on
```

if you interested with changes
https://github.com/HillLiu/cloudflare-bash-util/commit/a17b3a62fee338c253ed07dfef46684abb55018d
